# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileObject',
        ),
    ]
